Q-13 Develop a program to implement the K-Nearest Neighbours (KNN)
algorithm on a given dataset related to student performance with
target as Result(student_performance.csv). The program should
perform the following tasks:

i. Read the given dataset into a dataframe.

ii. Separate the input features and the target class label (Result)

iii. Split the dataset into training and testing sets in the ratios 70:30,
60:40, 80:20.

iv. Implement the K-Nearest Neighbours (KNN) classification
algorithm for a suitable value of K.

v. Train the model using the training data and classify the test
samples.

vi. Evaluate the performance of the model using accuracy, precision,
F1 score and recall and show the confusion matrix.

vii. Use the trained model to predict the class label for new data
points.

In [189]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [190]:
df=pd.DataFrame(pd.read_csv("student_performance.csv"))
df.head()

   StudyHours  Attendance  Assignments  InternalMarks Result
0         5.6          48           73             64   Pass
1         7.4          45           51             26   Fail
2         3.6          67           36             26   Fail
3         7.2          57           63             68   Pass
4         7.9          88           79             34   Pass

In [191]:
le=LabelEncoder()
df['Result']=le.fit_transform(df['Result'])
df.head()

   StudyHours  Attendance  Assignments  InternalMarks  Result
0         5.6          48           73             64       1
1         7.4          45           51             26       0
2         3.6          67           36             26       0
3         7.2          57           63             68       1
4         7.9          88           79             34       1

In [192]:
x=df.drop('Result',axis=1)
y=df['Result']
y.value_counts()

Result
1    200
0    200
Name: count, dtype: int64

In [193]:
ss=StandardScaler()
df_model=pd.DataFrame(ss.fit_transform(x),columns=x.columns)
df_model.head()

   StudyHours  Attendance  Assignments  InternalMarks
0    0.115719   -1.357046     0.391763       0.176178
1    0.789268   -1.531829    -0.670318      -1.499605
2   -0.632668   -0.250086    -1.394464      -1.499605
3    0.714429   -0.832696    -0.091001       0.352576
4    0.976365    0.973397     0.681422      -1.146808

In [194]:
model=KNeighborsClassifier()

In [195]:
sizes=[0.2,0.3,0.4]
for i in sizes:
  x_train,x_test,y_train,y_test=train_test_split(df_model,y,test_size=i,random_state=42)
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)
  accuracy = accuracy_score(y_test, y_pred)
  precision = precision_score(y_test, y_pred)
  f1 = f1_score(y_test, y_pred)
  recall = recall_score(y_test, y_pred)
  conf_matrix = confusion_matrix(y_test, y_pred)
  print(f"Test Size: {i}")
  print(f"Accuracy: {accuracy:.4f}")
  print(f"Precision: {precision:.4f}")
  print(f"Recall: {recall:.4f}")
  print(f"F1 Score: {f1:.4f}")
  print(f"Confusion Matrix:\n{conf_matrix}")
  print("\n")

Test Size: 0.2
Accuracy: 0.8875
Precision: 0.8696
Recall: 0.9302
F1 Score: 0.8989
Confusion Matrix:
[[31  6]
 [ 3 40]]


Test Size: 0.3
Accuracy: 0.9000
Precision: 0.9091
Recall: 0.9091
F1 Score: 0.9091
Confusion Matrix:
[[48  6]
 [ 6 60]]


Test Size: 0.4
Accuracy: 0.8938
Precision: 0.9186
Recall: 0.8876
F1 Score: 0.9029
Confusion Matrix:
[[64  7]
 [10 79]]

In [196]:
new_student = [[5.5, 80, 75, 70]]
test=ss.transform(new_student)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [197]:
prediction=model.predict(test)[0]
print("Prediction : ",end='')
if prediction:
  print("Pass")
else:
  print("Fail")

Prediction : Pass

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(